name: Run e2e Cypress tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  APP_ID: ${{ secrets.APP_ID }}

  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}

  APP_CHECK_DEBUG_TOKEN_FROM_CI: ${{ secrets.APP_CHECK_DEBUG_TOKEN_FROM_CI }}

  RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
  RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}

  RECAPTCHA_V3_SITE_KEY: ${{ secrets.RECAPTCHA_V3_SITE_KEY }}
  RECAPTCHA_V3_SECRET_KEY: ${{ secrets.RECAPTCHA_V3_SECRET_KEY }}

jobs:
  cypress:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Run e2e Cypress tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn dev
          start: yarn cypress:run
          wait-on: http://localhost:3000
